[package]
name = "fconx-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fconx = { path = "../fconx/" }

tokio = { version = "1.17.0", features = ["full"] }
flume = "0.10.14"

ctrlc = "3.2.2"
